# Estágio de Execução do Backend Node.js
FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
# Instala as dependências de produção apenas
RUN npm install --omit=dev
COPY . .
EXPOSE 3000
CMD ["node", "src/server/index.js"]
